plugins:
  - jekyll-paginate
  - jekyll-sitemap 
paginate: 5
paginate_path: "/announcements/:num/"

timezone: America/New_York

defaults:
  -
    scope:
      path: ""
    values:
      order: 1000

markdown: kramdown
kramdown:
  math_engine: mathjax # or katex
  syntax_highlighter: rouge